# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: ./gradlew dependencies
      - run: ./gradlew test
      - run: ./gradlew build
      - store_test_results:
          path: ["mocha-client/build/reports/tests/test/"]